### ISSUE TITLE
about data

### ISSUE THREAD

**Issue by superfly-zhang** [Jackustc/Question-Level-Feature-Extraction-on-DAIC-WOZ-dataset#1]
Hello, my team and I have been working on this data set recently, but we are missing some data（train_split_Depression_AVEC2017.csv，dev_split_Depression_AVEC2017.csv， test_split_Depression_AVEC2017.csv）, can you share it?

**Comment by Jackustc** [comment]
Hi, all of the data can be found in the link of http://dcapswoz.ict.usc.edu/ and I remember that you may need to fill out a kind of request form.
